language: python
arch:
   - ppc64le
   - amd64
env: 
   - TEST_TYPE=test
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
matrix:
    include:
        - arch:ppc64le
          python: 2.7
          env: TEST_TYPE=check
	    -  arch:amd64
		    python: 2.7
          env: TEST_TYPE=check
          
sudo: false
install:
  - if [[ $TEST_TYPE == 'check' ]]; then pip install -r requirements-dev.txt; fi
  - python scripts/ci/install
script:
  - make $TEST_TYPE
